# This is a basic workflow to help you get started with Actions

name: actions

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, 'main-hilt' ]
  pull_request:
    branches: [ main, 'main-hilt' ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.3.4

      - name: Setup Java JDK
        uses: actions/setup-java@v2.0.0
        with:
          java-version: '8'
          distribution: 'adopt'

      # WARNING: avoid run check function in large projects. It's an expansive task. I'll change this in the future.
      - name: Run all check tasks
        run: ./gradlew check

      # WARNING: building one feature only. Update in the future
      - name: Build debug APK on development flavor
        run: ./gradlew :applications:norris-facts:ui:assembleDevDebug
